import os
import json
from pathlib import Path
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_community.tools.tavily_search import TavilySearchResults

# 1. Gestion des chemins et du .env
# On remonte d'un dossier pour trouver le .env qui est à la racine
env_path = Path(__file__).resolve().parent.parent / 'backend' / '.env'
load_dotenv(dotenv_path=env_path)

# 2. Vérification des clés
api_key = os.getenv("OPENROUTER_API_KEY")
tavily_key = "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" 

if not api_key:
    print(" Erreur : Clé OPENROUTER_API_KEY non trouvée dans le .env")
    exit()

os.environ["TAVILY_API_KEY"] = tavily_key

class AudiDataFinder:
    def __init__(self):
        # Utilisation d'un modèle performant pour la synthèse
        self.llm = ChatOpenAI(
            model="mistralai/mistral-small-3.1-24b-instruct",
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key,
            temperature=0
        )
        self.search = TavilySearchResults(k=10)

    def get_contacts(self, country):
        print(f"\n Investigation approfondie pour Audi {country}...")
        
        # Stratégie Multi-Requêtes pour maximiser les chances de trouver des numéros directs
        queries = [
            f"Audi {country} Board of Management names and executive office contact",
            f"Audi {country} Investor Relations contact email phone shareholder services",
            f"Audi {country} executive customer care head of after-sales direct contact",
            f"Audi recall 4N0903028H technical support contact {country}"
        ]
        
        raw_data = ""
        for q in queries:
            try:
                res = self.search.run(q)
                raw_data += str(res) + "\n"
            except:
                continue

        # Étape 2 : Synthèse par l'IA avec instructions métier
        prompt = f"""
        CONTEXT: The CEO needs to escalate a critical technical failure (Part 4N0 903 028 H).
        DATA SOURCE: {raw_data}
        
        TASK:
        Extract a contact list for Audi {country} in a clean Markdown table.
        Columns: Name/Department, Role, Email, Phone/Executive Line.
        
        RULES:
        1. Look for 'Vorstand' (Board), 'Investor Relations', and 'Executive Support'.
        2. If a direct email is missing, provide the general executive office email.
        3. For Audi Germany, look for the 'Kundenbetreuung' executive level.
        4. For Audi Morocco, focus on 'Centrale Automobile Chérifienne' (CAC) leadership.
        
        Format: ONLY the Markdown table. No text before or after.
        """
        
        try:
            response = self.llm.invoke(prompt)
            return response.content
        except Exception as e:
            return f" Erreur IA : {e}"

if __name__ == "__main__":
    finder = AudiDataFinder()
    
    # On cible les zones demandées
    zones = ["Germany (Headquarters)", "Spain", "Morocco"]
    
    print(" DÉMARRAGE DE L'AGENT DE RECHERCHE CEO...")
    
    with open("audi_contacts_report.md", "w", encoding="utf-8") as f:
        f.write("#  Audi Executive Contact Report\n")
        f.write("Generated by AI Research Agent for CEO Urgency\n\n")
        
        for zone in zones:
            results = finder.get_contacts(zone)
            print(results)
            f.write(f"## {zone}\n{results}\n\n")
            print("-" * 50)

    print("\n Rapport généré : internal_tools/audi_contacts_report.md")